### ISSUE TITLE
IP issue

### ISSUE THREAD

**Issue by BroadNetworks** [MadaMzandu/ucrm-uisp-routeros-pppoe#13]
Have an issue where the API suddenly stopped working.
[php7:notice] [pid 10181] [client 172.18.251.2:33788] PHP Notice:  Trying to get property 'ip' of non-object in /var/www/html/lib/mt.php on line 34

worked around it by adding the Mikrotik IP into mt.php for the time being.

**Comment by MadaMzandu** [comment]
This is usually caused by invalid json in the devices.json file. Take note that json does not allow for trailing commas. Review your json file closely or use an online validator to make sure the json file does not contain invalid characters. The next version will move the devices file to a database and hopefully this problem will no longer be encountered.

**Comment by janvanrooy1** [comment]
I have the same issue, this happened without any recent changes to the devices.json file. @BroadNetworks please share how you changed line 34 in mt.php, I am struggling to get the format correct.

**Comment by BroadNetworks** [comment]
@MadaMzandu it was working fine and then all of a sudden a few days later it stopped working without any changes.

I appreciate the response and your effort to make this API work,it is bridging a gap between UISP & Mikrotik which many Mikrotik users will greatly appreciate.

Ill wait for your updates to a SQL based config and test it out when its ready!

**Comment by BroadNetworks** [comment]
@janvanrooy1 its kind of inefective because it limits you to only 1 Device that will be connected to via the API.
but my line 34 on mt.php is         $ip = "10.100.100.1";

**Comment by janvanrooy1** [comment]
I thought it might limit me to only 1 Routerboerd, I am still in testing phase, so for now it is ok, I also e-mailed Mada about the problem, just waiting for his reply.

**Comment by BroadNetworks** [comment]
@MadaMzandu i did validate the devices.json and it came back as valid

**Comment by MadaMzandu** [comment]
Thanks both for your feedback. Is anyone able to provide teamviewer/anydesk access so we can debug. You can use my profile email address to link.

Thanks

**Comment by BroadNetworks** [comment]
Yes I can provide anydesk in 15 minutes. Let me know if this is good for you

**Comment by janvanrooy1** [comment]
Thanks Mada, sent you my Anydesk details via E-Mail

**Comment by MadaMzandu** [comment]
Ok we managed to sort out Jan's problem. It was not a bug, so he is up and running.

@ BroadNetworks are you able to provide teamviewer/anydesk as well?

**Comment by janvanrooy1** [comment]
@MadaMzandu Thank you for your help today, Now that I understand how the "Device Name" option is used I was able to quickly setup my other high sites too

**Comment by BroadNetworks** [comment]
am i correct in saying the device name needs to relate to the device name in the json file?

**Comment by janvanrooy1** [comment]
Yes, and it is Case sensitive if I understand correctly.

**Comment by BroadNetworks** [comment]
ok that has cleared it up for me then as I tested that a minute ago and API was successful. 
Makes sense and was an oversight on my end.
Thanks for the help

**Comment by MadaMzandu** [comment]
> Yes, and it is Case sensitive if I understand correctly.

Just to correct this. The Device Name is not case sensitive. SITE1 and Site1 will resolve to the same device. This is in case the operator creating the accounts is not consistent.

Thanks All
