### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by lupael** [MadaMzandu/ucrm-uisp-routeros-pppoe#14]
I am preparing a small VPS server (Azure) for demo. Where UCRM and your plugin will be installed. This will allow others to login and test realtime usage. But is there anyone who would donate a CHR?

**Comment by MadaMzandu** [comment]
Hi Lupael,

Nice to hear from you again. Thats a good idea. Lets see if we can organize a CHR.

**Comment by MadaMzandu** [comment]
Hi Lupael,
The CHR is now available. Please use my personal contact to get the details.

Thnks
