### ISSUE TITLE
Manual IP Address still mandatory

### ISSUE THREAD

**Issue by raymondv2109** [MadaMzandu/ucrm-uisp-routeros-pppoe#17]
Users can not be make on the mikrotik whenever i don't fill the manual ip address field. Need improvement on this part.

**Comment by MadaMzandu** [comment]
Hi Raymond
Thanks for your feedback and I am looking at your problem.  Please use the following link to follow up because this version is no longer recommended for production.

https://github.com/MadaMzandu/uisp-ros-plugin/issues/10

Thanks

**Comment by MadaMzandu** [comment]
I am not able to reproduce this problem, are you using pppoe or dhcp?
